services:
  gateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - lb 
  lb:
    build: 
      context: .
      dockerfile: /DiscoveryService/Dockerfile
    ports:
      - "8761:8761"
  user-service:
    build: 
      context: .
      dockerfile: /UserService/Dockerfile
    ports:
      - "8010:8010"
    depends_on:
      - lb
      - db
  email-service:
    build: 
      context: .
      dockerfile: /EmailService/Dockerfile
    ports:
      - "8020:8020"
    depends_on:
      - lb
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: userpass
      MYSQL_DATABASE: ecom